config/routes.rb
Rails.application.routes.draw do
  get 'park_assets/index'
  get 'park_assets/show'
=begin
    get 'park_assets/index'
    get 'park_assets/show'
    get 'park_spaces/index'
    get 'park_spaces/show'
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Defines the root path route ("/")
    # root "articles#index"
=end

  resources :park_spaces, only: [:index, :show]
  resources :park_assets, only: [:index, :show]
  get 'about', to: 'about#index'


  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/park_asset.rb
class ParkAsset < ApplicationRecord
  self.primary_key = 'asset_id'
  belongs_to :park_spaces, foreign_key: "park_id", class_name: 'ParkSpace'
  validates :park_name, presence: true
end

app/models/park_space.rb
class ParkSpace < ApplicationRecord
 self.primary_key = 'park_id'
 has_many :park_assets, foreign_key: "park_id"
 has_one :spray_pads, class_name: "Pool", foreign_key: "park_id"
 has_one :pools, class_name: "Pool", foreign_key: "park_id"
 validates :park_name, presence: true
end

app/models/pool.rb
class Pool < ApplicationRecord
  belongs_to :park_spaces, foreign_key: "park_id", class_name: 'ParkSpace'
  validates :park_name, presence: true
end

app/models/spray_pad.rb
class SprayPad < ApplicationRecord
  belongs_to :park_spaces, foreign_key: "park_id", class_name: 'ParkSpace'
  validates :park_name, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/park_assets_controller.rb
class ParkAssetsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/park_spaces_controller.rb
class ParkSpacesController < ApplicationController
  def index
    @park_spaces = ParkSpace.all
    @park_spaces = ParkSpace.includes(:park_assets)

    @park_spaces = ParkSpace.includes(:pools)

    #Simple Search
    @park_spaces = @park_spaces.where("park_name LIKE ?", "%#{params[:q]}%") if params[:q].present?

    @park_spaces = @park_spaces.where(neighbourhood: params[:neighbourhood]) if params[:neighbourhood].present?

    @park_spaces = @park_spaces.page(params[:page]).per(25)
  end


    #@park_space = ParkSpace.find(params[:id])

    def show
      @park_space = ParkSpace.find(params[:id])
      @park_assets = @park_space.park_assets
      @pool = @park_space.pools
      @spray = @park_space.spray_pads

    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/park_assets_helper.rb
module ParkAssetsHelper
end

app/helpers/park_spaces_helper.rb
module ParkSpacesHelper
end

app/views/about/index.html.erb
<div class="banner flex justify-between items-center">
  <h1 class="text-white text-3xl font-bold">Park Spaces in Winnipeg</h1>

  <div class="menu">
    <%= link_to "About", about_path, class: "text-white font-bold mr-4" %>
    <%= link_to "Park Spaces", park_spaces_path, class: "text-white font-bold" %>
  </div>
</div>


<div>
<h1 class="text-3xl font-bold mb-2">About Us</h1>
<p style="display: block; clear: both;"><strong>The information below are from the open data source of Winnipeg.</strong></p><br>
<p>The Park and Open Space and Park Assets Inventory has an association through the park_id. One park has many park assets, and has one to zero pool
    & spray pad.</p>
<br>
  <div>
    <h2 class="text-2xl font-bold mb-4">Park and Open Space</h2>
      <div class="ml-4">
      <p>This dataset has information about all the parks and open spaces around Winnipeg.
      This includes the park name, address, district neighbourhood, electoral ward,
      and the measurement of the park’s area.</p>
        <ul class="list-disc list-inside m-2">
        <strong>Table: park_names</strong>
	       <li>park_id, park_name
	           address, location_description,
	           linear_park_system, district,
          <br>
	           neighbourhood, electoral_ward,
	           cca, area_in_hectares,
	           water_in_hectares, land_area_in_hectares</li>
        </ul>
      </div>

    <br>

    <h2 class="text-2xl font-bold mb-4">Park Assets</h2>
      <div class="ml-4">
      <p>This dataset has the asset inventory for the parks such as benches and play structures.</p>
        <ul class="list-disc list-inside m-2">
        <strong>Table: park_assets</strong>
	       <li>asset_id, asset_class, asset_type,
             park_id, park_name, primary_field</li>
        </ul>
      </div>

    <br>

    <h2 class="text-2xl font-bold mb-4">Pools</h2>
      <div class="ml-4">
      <p>This dataset has the information of the outdoor swimming pools in Winnipeg and its amenities.</p>
        <ul class="list-disc list-inside m-2">
        <strong>Table: pools</strong>
	       <li>id, park_id, park_name, address, is_open,
             avg_temp, group_bookings, lockers, slide,
             diving_board, lap_swim,
             <br>
             lessons, spray,
             showers, parking_lot, booking_info, locker_info, complex_id
          </li>
        </ul>
      </div>
    <br>

    <h2 class="text-2xl font-bold mb-4">Spray Pad</h2>
      <div class="ml-4">
      <p>This dataset has the park names where spray pads are available and if it is open.</p>
        <ul class="list-disc list-inside m-2">
        <strong>Table: spray_pads</strong>
	       <li>id, park_id, park_name, address, is_open,
             complex_id
          </li>
        </ul>
        <br>
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Parkproject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>

     <div class="bg-blue-500 text-white py-8 px-2  style=position: fixed; bottom: 0; left: 0; right: 0;">
         <p class="text-center">&copy; 2023 Park Spaces in Winnipeg</p>
     </div>
  </body>
</html>

app/views/park_assets/index.html.erb
<h1>ParkAssets#index</h1>
<p>Find me in app/views/park_assets/index.html.erb</p>

app/views/park_assets/show.html.erb
<h1>ParkAssets#show</h1>
<p>Find me in app/views/park_assets/show.html.erb</p>

app/views/park_spaces/index.html.erb
<div class="banner flex justify-between items-center">
  <h1 class="text-white text-3xl font-bold">Park Spaces in Winnipeg</h1>

  <div class="menu">
    <%= link_to "About", about_path, class: "text-white font-bold mr-4" %>
    <%= link_to "Park Spaces", park_spaces_path, class: "text-white font-bold" %>
  </div>
</div>


<div>
<div class="flex justify-between items-center mb-4" style="position: absolute; top: 4; right: 1.5rem;">
  <%= form_tag park_spaces_path, method: :get, class: "flex-1 mr-4" do %>
    <div class="flex items-center">
      <%= text_field_tag :q, params[:q], placeholder: "Search by park name", class: "form-control mr-1" %>
      <%= select_tag :neighbourhood, options_for_select(ParkSpace.pluck(:neighbourhood).uniq, params[:neighbourhood]), prompt: "Select a neighborhood", class: "form-control ml-2" %>
      <%= submit_tag "Search", class: "btn btn-primary bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded ml-2" %>
    </div>
  <% end %>
</div>


<div>
  <h1 class="text-2xl font-bold mb-4"> Do you know that there are a thousand of park spaces in Winnipeg?</h1>
    <ul class="mt-8" style="width: 100%">
        <% @park_spaces.each do |park_space| %>
           <li class="flex justify-between items-center">
               <%= link_to park_space.park_name, park_space_path(park_space) %>
               <% if park_space.pools.present? %>
                <span class="text-green-500 font-bold text-center">Pool is available</span>
               <% end %>
           </li>
        <% end %>
   <br>
   <div class="pagination">
      <%= paginate @park_spaces %>
   </div>
   </ul>
<br>
</div>

app/views/park_spaces/show.html.erb
<div class="container flex flex-col min-h-screen">
  <div class="flex-grow">
    <div class="banner">
  <h1 class="text-white text-3xl font-bold">Park Spaces in Winnipeg</h1>
  <br>
  <div class="flex justify-between items-center mb-2"  style="position: absolute; right: 1rem; top: 3.5rem;  ">
    <%= link_to "About", about_path, class: "text-white font-bold mr-4" %>
    <%= link_to "Park Spaces", park_spaces_path, class: "text-white font-bold" %>
  </div>

</div>

<div class="max-w-2xl  py-10 px-10">
  <h1 class="text-2xl font-bold mb-4"><%= @park_space.park_name %></h1>

  <div class="border-b-2 border-gray-200 pb-4 mb-4">
    <p class="text-gray-600"><%= @park_space.neighbourhood %></p>
    <p class="text-gray-600"><%= @park_space.electoral_ward %></p>
    <p class="text-gray-600"><%= @park_space.location_description %> Winnipeg</p>
  </div>

<!-- Spray Pad -->
<div class="border-b-2 border-gray-200 py-4 mb-4">
    <h2 class="text-lg font-bold mb-2">Spray Pad Feature</h2>
      <% if @spray.present? %>
        <p class="text-gray-600">Spray Pad Status: <%= @spray.is_open ? 'Open' : 'Closed or Not Available' %></p>
          <% else %>
        <p class="text-gray-600">No spray pad information available for this park.</p>
      <% end %>
</div>

<!-- Park Assets -->
<div class="border-b-2 border-gray-200 py-4 mb-4">
  <h2 class="text-lg font-bold mb-2">Park Assets:</h2>
  <% if @park_assets.any? %>
    <% @park_assets.group(:asset_type).count.sort_by { |asset_type, count| asset_type.downcase }.each do |asset_type, count| %>
      <% if asset_type == "N/A" %>
        <% asset_type = "Others" %>
      <% end %>
      <p class="text-gray-600"><%= "#{asset_type.capitalize}: #{count}" %></p>
    <% end %>
  <% else %>
    <p class="text-gray-600">No park assets found for this park space.</p>
  <% end %>
</div>

<!-- Pools -->
<% if @pool.present? %>
  <div class="mr-5">
      <h2 class="text-lg font-bold mb-2">Pool Information</h2>
        <p class="text-gray-600"><strong>Pool Entry:</strong> <%= @pool.pool_entry %></p>
        <p class="text-gray-600"><strong>Pool Entry Height:</strong> <%= @pool.entry_height %></p>
        <p class="text-gray-600"><strong>Average Water Temperature:</strong> <%= @pool.avg_temp %></p>
        <p class="text-gray-600"><strong>Group Booking:</strong>
          <% if @pool.group_bookings == "TRUE" %>
            <p><%= @pool.booking_info.capitalize%></p>
          <% else %>
            <p>Booking ahead is not necessary.</p>
          <% end %>
          <p class="text-gray-600"><strong>Locker Information:</strong>
          <% if @pool.locker_info == "TRUE" %>
            <p><%= @pool.locker_info%></p>
          <% else %>
            <p>This pool location do not have locker available.</p>
          <% end %>
          <p class="text-gray-600"><strong>Slide:</strong>
          <% if @pool.slide == "TRUE"%>
            <p>This pool location has a slide.</p>
          <% else %>
            <p>This pool location do not have slide.</p>
          <% end %>
        </div>
        <% else %>
            <h2 class="text-lg font-bold mb-2">Pool Information</h2>
            <p>No pool information available for this park.</p>
    <% end %>
  </div>
</div>
</div>

<!-- Park Names  -->
<div class="max-w-2xl mx-auto flex justify-between mt-8">
  <div class="w-1 mr-40 ml-30">
    <!-- existing code for park space details -->
  </div>

  <div class="w-60 ml-50">
    <h2 class="text-lg font-bold mb-2">Other Park Spaces:</h2>
      <ul>
        <% ParkSpace.order(Arel.sql('RANDOM()')).limit(6).each do |park_space| %>
          <li><%= link_to park_space.park_name, park_space_path(park_space) %></li>
      <% end %>
      </ul>
    <br>
  </div>